# Generated by Django 3.2.8 on 2021-10-24 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Word', models.CharField(max_length=30, verbose_name='word')),
                ('morfo', models.TextField(max_length=100, verbose_name='morfo')),
                ('morfema', models.TextField(max_length=100, verbose_name='morfema')),
                ('translation', models.TextField(max_length=100, verbose_name='translation')),
                ('lexical_translation', models.TextField(max_length=300, verbose_name='lexical_translation')),
                ('observations', models.TextField(max_length=300, verbose_name='observations')),
                ('creation_date', models.DateTimeField(null=True)),
                ('last_modification', models.DateTimeField(null=True)),
                #('tribe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tribe', to='dictionaryApp.tribe')),
                #('user_responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_responsible', to=settings.AUTH_USER_MODEL)),
                #('word_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Word_Type', to='dictionaryApp.wordtype')),
            ],
        ),
    ]
