# Generated by Django 3.2.8 on 2021-11-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='Word',
        ),
    ]
