# Generated by Django 3.2.7 on 2021-11-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
