# Generated by Django 3.2.7 on 2021-11-20 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_auto_20211112_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefono',
        ),
    ]
