# Generated by Django 3.2.7 on 2021-11-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_auto_20211120_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(default=None, max_length=30, verbose_name='Telefono'),
        ),
    ]
