# Generated by Django 3.2.7 on 2021-11-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activo',
            field=models.CharField(default=None, max_length=30, verbose_name='Activo'),
        ),
    ]
